# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9
language: swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
#- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/ImmutableGraph.xcworkspace -scheme ImmutableGraph-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint
script:
  - xcodebuild -scheme ImmutableGraph-Example -workspace Example/ImmutableGraph.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=11' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
