
osx_image: xcode9

language: swift

# cache: cocoapods

# podfile: Example/Podfile

# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example

script:
  - xcodebuild -scheme ImmutableGraph-Example -workspace Example/ImmutableGraph.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=11.0' build test
  - pod lib lint

after_success:
  - bash <(curl -s https://codecov.io/bash)
